### ISSUE TITLE
[Todo]APP 설계

### ISSUE THREAD

**Issue by leejeongeun0** [ehdcjf4874/2022_Capstone-Design#3]
**<필수 설계>**

- 시작화면
- 회원가입
- 로그인
- 메인화면

**<추가 설계>**

- 커뮤니티 기능

**Comment by leejeongeun0** [comment]
<회원가입P 필수기능>
- 이메일 입력창
- 이메일 확인 버튼 -> 중복 이메일 가입불가
- 비밀번호 입력창
- 비밀번호 확인창 -> 비밀번호 일치여부 확인
- 회원가입 완료 버튼 -> 로그인P 이동
- 
![02_회원가입P](https://user-images.githubusercontent.com/75784140/169750462-72ee0522-26a0-4624-b6cd-3a1ab681efa0.png)

**Comment by leejeongeun0** [comment]
<로그인P 필수기능>
- 이메일 입력창
- 비밀번호 입력창
- 로그인 확인 버튼 ->성공시 메인화면 OR 실패시 재시도 안내창


![03_로그인P](https://user-images.githubusercontent.com/75784140/169750521-056dd899-ab6f-49fb-94c6-af21aadcce46.png)

**Comment by leejeongeun0** [comment]
<메인화면P 필수기능>
- 핑거프린트 기능을 활용하여 위치에 따라 이미지 화면 출력
- 음성인식 시작 버튼 


![캡디_보이스_갤러리  메인P](https://user-images.githubusercontent.com/75784140/169751026-ec1fa300-e28e-4fb0-9d1b-c268b9fe38c0.png)

**Comment by leejeongeun0** [comment]
<시작화면P 필수기능>
- 회원가입 버튼 -> 회원가입P 이동
- 로그인 버튼 -> 로그인P 이동


![01_시작화면P](https://user-images.githubusercontent.com/75784140/169751147-27964a6a-77aa-425e-b939-bf9b27506364.png)

**Comment by ehdcjf4874** [comment]
수정사항 없을것같습니다.
